import type { Metadata } from 'next';
import { ClerkProvider } from '@clerk/nextjs';
import { Inter } from 'next/font/google';
import '../globals.css';

import SidePanel from '@/components/shared/SidePanel';
import Header from '@/components/shared/Header';
import NavBar from '@/components/shared/Navbar';
import Footer from '@/components/shared/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Threads Clone',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang='en'>
				<body className={inter.className}>
					<Header />
					<main>
						<NavBar />
  						<section className='main-container'>
  							<div className='w-full max-w-4xl'>{children}</div>
  						</section>
						<SidePanel />
					</main>
					<Footer />
				</body>
			</html>
		</ClerkProvider>
	);
}
