import type { Metadata } from 'next';
import { ClerkProvider } from '@clerk/nextjs';
import { Inter } from 'next/font/google';
import '../globals.css';

import RightSidebar from '@/components/shared/RightSidebar';
import Header from '@/components/shared/Header';
import SideNavBar from '@/components/shared/SideNavBar';
import BottomNavBar from '@/components/shared/BottomNavBar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Threads Clone',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang='en'>
				<body className={`${inter.className} w-full h-full`}>
					<Header />
					<main className='flex flex-row'>
						<SideNavBar />
  						<section className='main-container'>
  							<div className='w-full max-w-4xl'>{children}</div>
  						</section>
						<RightSidebar />
					</main>
					<BottomNavBar />
				</body>
			</html>
		</ClerkProvider>
	);
}
